moved the url step

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -10,16 +10,16 @@ jobs:
           node-version: "14.x"
       - run: |
           yarn install
-      - name: run Lighthouse CI
-        run: |
-          yarn global add @lhci/cli@0.8.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
-        # We need to integrate https://github.com/zentered/vercel-preview-url to use this build instead of building in this test
         with:
         urls: |
           ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
         uploadArtifacts: true
         temporaryPublicStorage: true
+      - name: run Lighthouse CI
+        run: |
+          yarn global add @lhci/cli@0.8.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        # We need to integrate https://github.com/zentered/vercel-preview-url to use this build instead of building in this test
   
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
